#!/usr/bin/env bash

echo "[LOG] Beginning Build"

echo "rm -f .env"
rm -f .env

if [[ 'DEV' == ${ENV} ]]
then
    echo "[LOG] Environment Set To Development"
    echo "cp .env.dev .env"
    cp .env.dev .env
elif [[ 'TEST' == ${ENV} ]]
then 
    echo "[LOG] Environment Set To Test"
    echo "cp .env.test .env"
    cp .env.test .env
elif [[ 'PROD' == ${ENV} ]]
then
    echo "[LOG] Environment Set To Production"
    echo "cp .env.prod .env"
    cp .env.prod .env
fi

echo "REACT_APP_DATE_TIME='$(date)'" >> .env

echo "npm run build"
npm run build

echo "[LOG] Build Complete"