#!/usr/bin/env bash

if [[ $* == *-y* ]]
then
    ssh zeus "rm -rf ${DEPLOY_PATH}/*"
    scp -r ./build/* zeus:${DEPLOY_PATH}
    echo Done!
else
    read -p "Are you SURE you want to deploy, this cannot be undone? " -n 1 -r
    echo    # (optional) move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        ssh zeus "rm -rf /var/www/dev.collinmmeyer.com/html/*"
        scp -r ./build/* zeus:/var/www/dev.collinmmeyer.com/html

        echo Done!
    fi
fi