name: Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 19.3.0

      - name: Build React App
        run: |
          npm install
          npm run build
        env:
          CI: ""
      
      - name: Deploy to Cloud
        run: |
          echo "${{ secrets.SSH_KEY }}" > tempkey
          scp -i tempkey ./build/* -r ${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}