name: Test Deployment

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]
    name: Build and Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 19.3.0

      - name: Build React App
        run: |
          rm -f .env
          ln -s .env.test .env
          npm install
          make build
        env:
          CI: ""
      
      - name: Deploy to Cloud
        run: |
          DEPLOY_PATH=${{ secrets.TEST_TARGET_DIR }} ./deploy -y
